### ISSUE TITLE
Networking tut - hardcoding node-0 results in SPOF

### ISSUE THREAD

**Issue by sammcj** [docker/dceu_tutorials#23]
It looks to me like the networking tutorial has a SPOF in that the example suggests hard coding node-0's IP address into the docker config.

I would assume that if node-0 was unavailable you wouldn't be able to start the other nodes - is this correct and if so perhaps it's worth adding a note to point this out?

https://github.com/docker/dceu_tutorials/blob/master/6-networking.md#task-2-configure-the-engine-to-use-key-value-store

**Comment by nicolaka** [comment]
@sammcj Your assumption is correct. We have to tell the nodes which cluster-store to use. In this case it's the consul server running as a container on node-0. I'll add a comment to point that out.
